name: Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Run Snyk to check for Go vulnerabilities
        uses: snyk/actions/golang@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Container test
        uses: snyk/actions/docker@master
        with:
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/terramock-docker-registry/terramock-app-frontend:1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
